name: deepgaze-entropy-reg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - opencv>=4.7.0
  - scikit-image>=0.20.0
  - pyyaml>=6.0
  - pip
  - pip:
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
